name: Simple App Deployment to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 52.147.201.2
        username: azureuser
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker stop $(sudo docker ps -q)
          sudo rm -rf /home/azureuser/app
          mkdir -p /home/azureuser/app
          exit 0

    - name: Upload Files via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 52.147.201.2
        username: azureuser
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/home/azureuser/app"

    - name: Start Docker Container
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 52.147.201.2
        username: azureuser
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/azureuser/app
          sudo docker build -t flask-app .
          sudo docker run -d -p 80:5000 flask-app
